[listener]
type="socket"

[director.cowrie-ssh]
type="forward"
host="cowrie:2222"

[director.sshd]
type="forward"
host="sshd:2223"

[service.sshproxy1]
type="ssh-proxy"
director="cowrie-ssh"
credentials=["*"]

[[port]]
port="tcp/8022"
services=["sshproxy1"]

[service.sshproxy2]
type="ssh-proxy"
director="sshd"
credentials=["*"]

[[port]]
port="tcp/8023"
services=["sshproxy2"]

[service.ethereum]
type="ethereum"

[[port]]
port="tcp/8545"
services=["ethereum"]

[channel.console]
type="console"

[channel.elasticsearch]
type="elasticsearch"
url="http://elasticsearch:9200/honeytrap"

[[filter]]
channel=["console", "elasticsearch"]

[[logging]]
output = "stdout"
level = "debug"
